# Colección de ejercicios de Numpy

## 1 - Importa el paquete con el nombre "np".

`pista: import … as …`

In [1]:
import numpy as np 

## 2 - Imprime la versión instalada.

`pista: np.__version__, np.show_config`

In [2]:
np.__version__

'2.0.2'

In [3]:
np.show_config

<function numpy.__config__.show(mode='stdout')>

## 3 - Crea un vector de nulos de tamaño 10.

`pista: np.zeros`

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

## 4 - Encontrar el tamaño en memoria de un array.

`pista: size, itemsize`

In [5]:
arr = np.array([1, 2, 3, 4, 5]) # primero creo que el array
print(arr.size) #me da el numero de elementos del array
print(arr.itemsize) #me da el peso de cada elemento
#para calcular el peso multiplico uno por otro para que me de el total

tamaño_memoria = arr.size * arr.itemsize
print(f'El tamaño de {arr} es de {tamaño_memoria} bytes')

5
8
El tamaño de [1 2 3 4 5] es de 40 bytes


## 5 - Cree un vector nulo de tamaño 10 pero el quinto valor tiene de valor 1.

`pista: array[...]`

In [6]:
vector2 = np.zeros(10) 
vector2[4] = 1
print(vector2)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


## 6 - Cree un vector con valores que van de 10 a 49.

`pista: arange`


In [7]:
vector3 = np.arange(10,50)
vector3

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

## 7 - Invierta un vector (el primer elemento se convierte en el último).

`pista: array[::-1]`

In [8]:
print(vector3[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


## 8 Cree una matriz de 3x3 con valores que van de 0 a 8.

`pista: reshape`

In [9]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 9 - Encuentre los índices de elementos distintos de cero de `[7,5,0,0,2,1]`.

`pista: np.nonzero`

In [10]:
#el ejercicio me pide los indices, es decir la posición de los que no son ceros. np.zero lo hace automaticamente
vector4= [7,5,0,0,2,1]
np.nonzero(vector4)
print(np.nonzero(vector4)[0]) # le pongo el [0] para que me lo devuelva en formato lista

[0 1 4 5]


## 10 - Crear una matriz de identidad de 3x3.

`pista: np.eye`


In [11]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## 11 - Crear una matriz de 3x3x3 con valores aleatorios.

`pista: np.random.random`


In [12]:
np.random.random((3,3,3)).round(2)

array([[[0.13, 0.9 , 0.87],
        [0.61, 0.51, 0.71],
        [0.01, 0.53, 0.86]],

       [[0.23, 0.75, 0.85],
        [0.67, 0.96, 0.43],
        [0.53, 0.22, 0.47]],

       [[0.08, 0.23, 0.97],
        [0.33, 0.11, 0.89],
        [0.55, 0.79, 0.8 ]]])

## 12 - Cree una matriz de 10x10 con valores aleatorios y encuentre el mínimo y el máximo.

`pista: min, max`

In [13]:
matriz_10_x_10 = np.random.random((10,10)).round(2)
print(matriz_10_x_10)
print(matriz_10_x_10.min())
print(matriz_10_x_10.max())

[[0.14 0.9  0.2  0.93 0.96 0.14 0.85 0.66 0.9  0.5 ]
 [0.7  0.51 0.17 0.73 0.39 0.96 0.32 0.15 0.69 0.52]
 [0.   0.48 0.64 0.34 0.32 0.35 0.95 0.96 0.99 0.49]
 [0.4  0.61 0.16 0.69 0.6  0.06 0.86 0.61 0.79 0.85]
 [0.48 0.04 0.81 0.21 0.18 0.86 0.48 0.03 0.91 0.4 ]
 [0.28 0.85 0.59 0.26 0.02 0.16 0.8  0.67 0.9  0.49]
 [0.82 0.71 0.99 0.66 0.54 0.22 0.12 0.06 0.3  0.66]
 [0.81 0.04 0.62 0.51 0.38 0.83 0.14 0.96 0.53 0.92]
 [0.51 0.77 0.71 0.85 0.44 0.89 0.61 0.41 0.8  0.56]
 [0.71 0.97 0.54 0.31 0.52 0.76 0.52 0.61 0.56 0.37]]
0.0
0.99


## 13 - Cree un vector aleatorio de tamaño 50 y encuentre el valor medio.

`pista: mean`

In [14]:
vector_aleatorio = np.random.random(50).round(2)
media = vector_aleatorio.mean().round(2)

print(vector_aleatorio)
print(f'El valor medio del vector es {media}')

[0.43 0.84 0.7  0.43 0.93 0.96 0.08 0.9  0.23 0.89 0.   0.04 0.05 0.51
 0.72 0.58 0.72 0.36 0.46 0.73 0.47 0.88 0.2  0.9  0.33 1.   0.21 0.84
 0.83 0.94 0.73 0.56 0.33 0.71 0.79 0.72 0.75 0.85 0.04 0.62 0.03 0.3
 1.   0.51 0.07 0.89 0.74 0.96 0.05 0.57]
El valor medio del vector es 0.57


## 14 - Cree una matriz de 6x6 con valores 1,2,3,4,5 justo debajo de la diagonal.

`pista: np.diag`

In [15]:
np.diag([1,2,3,4,5], k=-1)

array([[0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 5, 0]])

In [16]:
np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [17]:
#primero creo los valores que quiero colocar en la matriz
valores = np.array([1, 2, 3, 4, 5])
# despues usando np.diag coloco esos valores en la diagonal. esto se hace con k=0. k=0 indica el desplazamiento a la diagonal inferior inmediata, el numero me dice donde tiene que empezar
matriz = np.diag(valores, k=1)
print(matriz)


[[0 1 0 0 0 0]
 [0 0 2 0 0 0]
 [0 0 0 3 0 0]
 [0 0 0 0 4 0]
 [0 0 0 0 0 5]
 [0 0 0 0 0 0]]


In [18]:
#si por ejemplo uso k=1 empezaria en la posicion 2
matriz2 = np.diag(valores, k=1)
print(matriz2)

[[0 1 0 0 0 0]
 [0 0 2 0 0 0]
 [0 0 0 3 0 0]
 [0 0 0 0 4 0]
 [0 0 0 0 0 5]
 [0 0 0 0 0 0]]


## 15 - Considere una matriz de formas (4,5,6), ¿cuál es el índice (x,y,z) del elemento número 57?

`pista: np.unravel_index`

In [19]:
#para entenderlo pruebo con una matriz mas pequeña de 20
matriz = np.arange(20).reshape(5,4)
matriz


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [20]:
#si lo pongo asi es para pedirle la posicion 10
np.unravel_index(10, (5,4))

(np.int64(2), np.int64(2))

In [21]:
matriz456 = np.arange(120).reshape(4,5,6) #creo una matriz de 120 (que es 4*5*6) y le hago el reshape a 4,5,6, siendo 4 matrices de 5x6
print(matriz456)
np.unravel_index(57-1,(4,5,6)) #esto me da las coordenadas de la posicion 57. el resultado es 

[[[  0   1   2   3   4   5]
  [  6   7   8   9  10  11]
  [ 12  13  14  15  16  17]
  [ 18  19  20  21  22  23]
  [ 24  25  26  27  28  29]]

 [[ 30  31  32  33  34  35]
  [ 36  37  38  39  40  41]
  [ 42  43  44  45  46  47]
  [ 48  49  50  51  52  53]
  [ 54  55  56  57  58  59]]

 [[ 60  61  62  63  64  65]
  [ 66  67  68  69  70  71]
  [ 72  73  74  75  76  77]
  [ 78  79  80  81  82  83]
  [ 84  85  86  87  88  89]]

 [[ 90  91  92  93  94  95]
  [ 96  97  98  99 100 101]
  [102 103 104 105 106 107]
  [108 109 110 111 112 113]
  [114 115 116 117 118 119]]]


(np.int64(1), np.int64(4), np.int64(2))

## 16 - Normalice una matriz aleatoria de 10x10.

`pista: (x - mean) / std`

In [22]:
# normalizar significa mover la desviacion que tenga esa matriz una desviacion estandar de 0,1.  
matriz10 = 10*np.random.rand(10,10)+1,7
matriz

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [23]:
(matriz-matriz.mean())/matriz.std()

array([[-1.64750894, -1.47408695, -1.30066495, -1.12724296],
       [-0.95382097, -0.78039897, -0.60697698, -0.43355498],
       [-0.26013299, -0.086711  ,  0.086711  ,  0.26013299],
       [ 0.43355498,  0.60697698,  0.78039897,  0.95382097],
       [ 1.12724296,  1.30066495,  1.47408695,  1.64750894]])

In [24]:
# Generar una matriz aleatoria de 10x10
matriz = np.random.random((10, 10))

# Calcular la media y desviación estándar de la matriz
media = np.mean(matriz)
desviacion_std = np.std(matriz)

# Aplicar la normalización
matriz_normalizada = (matriz - media) / desviacion_std

print(matriz_normalizada)


[[ 0.30696075 -0.85766411 -0.44209161  0.17197287  0.99424972 -0.30286042
   0.31654364  0.91647828 -1.7374123   0.58815374]
 [ 1.28627537 -1.12990364  0.28747889 -0.78324685 -1.76504165 -0.17987567
   1.04485288  0.13178242 -0.98886077  1.4238604 ]
 [-0.29636284  1.68074784  1.42503768 -0.04982674 -1.21475454 -1.38729914
   0.14969614 -0.40390916 -0.73216536 -1.3402507 ]
 [ 0.76095998  0.2208625  -1.42230306  1.35846245 -1.77844106 -0.24729891
  -0.55993019 -0.28889507 -1.23924568  0.36248147]
 [-0.85823377  0.78930278 -0.76962813  0.56918733  1.4399231  -0.05672427
   0.10867074  0.50157065  1.32151472  1.42929502]
 [-0.39280183  0.25724782  1.13548119  1.13326195  0.95638308 -0.42824862
   1.45029274 -0.74158116 -0.44443569 -1.76589791]
 [ 1.2263118   0.41002885 -0.61751915  1.665518    1.51859016  1.36271291
   1.1940337   0.23830129  1.33388403 -0.7188236 ]
 [-1.64541358 -1.76007877 -1.72927687 -1.41742187  1.16573435 -1.62333798
  -0.90568821 -0.19275675 -0.28251293 -0.96193096]


## 17 - Multiplique una matriz de 3x2 por una matriz de 2x5.

In [25]:
np.dot(np.ones((3,2)),np.ones((2,5)))

array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

In [26]:
matriz3x2 = np.random.random((3,2))
matriz2x5 = np.random.random((2,5))

resultado = np.dot(matriz3x2, matriz2x5).round(2)
print(resultado)

[[0.41 0.26 0.21 0.3  0.13]
 [0.92 0.57 0.59 0.41 0.03]
 [0.9  0.58 0.41 0.76 0.39]]


## 18 - ¿Cómo encuentra valores comunes entre dos matrices?

`pista: np.intersect1d`


In [27]:
np.intersect1d(np.arange(0,50,5), np.arange(0,50,2))

array([ 0, 10, 20, 30, 40])

In [28]:
#primero creamos dos matrices
matriz_a = np.arange(1,7).reshape(2,3)
matriz_b = np.arange(4,10).reshape(2,3)

#despues hay que usar .flatten() para aplanar las matrices, esto no es necesario pero facilitaria la busqueda
matriz_a_flat = matriz_a.flatten()
matriz_b_flat = matriz_b.flatten()

#con np.intersect1d buscamos los valores comunes. 
valores_comunes = np.intersect1d(matriz_a_flat, matriz_b_flat)
print(valores_comunes)

[4 5 6]


In [29]:
#primero creamos dos matrices
matriz_c = np.arange(1,7).reshape(2,3)
matriz_d = np.arange(4,10).reshape(2,3)

#con np.intersect1d buscamos los valores comunes. 
valores_comunes2 = np.intersect1d(matriz_c, matriz_d)
print(valores_comunes2)

[4 5 6]


## 19 - ¿Cómo obtener las fechas de ayer, hoy y mañana?

`pista: np.datetime64, np.timedelta64`


In [30]:
today = np.datetime64('today')
yesterday = np.datetime64('today')-1
tomorrow = np.datetime64('today')+1


In [31]:
# Obtener la fecha de hoy
hoy = np.datetime64('today', 'D')

# Calcular las fechas de ayer y mañana
ayer = hoy - np.timedelta64(1, 'D')
manana = hoy + np.timedelta64(1, 'D')

# Mostrar las fechas
print("Fecha de ayer:", ayer)
print("Fecha de hoy:", hoy)
print("Fecha de mañana:", manana)


Fecha de ayer: 2024-10-05
Fecha de hoy: 2024-10-06
Fecha de mañana: 2024-10-07


In [32]:
from datetime import datetime, timedelta

# Obtener la fecha de hoy
hoy = datetime.now().date()

# Calcular las fechas de ayer y mañana
ayer = hoy - timedelta(days=1)
mañana = hoy + timedelta(days=1)

# Mostrar las fechas
print("Fecha de ayer:", ayer)
print("Fecha de hoy:", hoy)
print("Fecha de mañana:", mañana)


Fecha de ayer: 2024-10-05
Fecha de hoy: 2024-10-06
Fecha de mañana: 2024-10-07


## 20 - ¿Cómo obtener todas las fechas correspondientes al mes de septiembre de 2020?

`pista: np.arange(dtype=datetime64['D'])`

In [33]:
Z = np.arange('2020-09', '2020-10', dtype='datetime64[D]')
print(Z)

['2020-09-01' '2020-09-02' '2020-09-03' '2020-09-04' '2020-09-05'
 '2020-09-06' '2020-09-07' '2020-09-08' '2020-09-09' '2020-09-10'
 '2020-09-11' '2020-09-12' '2020-09-13' '2020-09-14' '2020-09-15'
 '2020-09-16' '2020-09-17' '2020-09-18' '2020-09-19' '2020-09-20'
 '2020-09-21' '2020-09-22' '2020-09-23' '2020-09-24' '2020-09-25'
 '2020-09-26' '2020-09-27' '2020-09-28' '2020-09-29' '2020-09-30']


In [34]:
# Definir el inicio y el final del mes de septiembre de 2020
inicio = np.datetime64('2020-09-01')
fin = np.datetime64('2020-10-01')  # El 1 de octubre como límite superior

# Generar las fechas de septiembre de 2020
fechas_septiembre = np.arange(inicio, fin, dtype='datetime64[D]')

# Mostrar las fechas
print("Fechas de septiembre de 2020:")
print(fechas_septiembre)


Fechas de septiembre de 2020:
['2020-09-01' '2020-09-02' '2020-09-03' '2020-09-04' '2020-09-05'
 '2020-09-06' '2020-09-07' '2020-09-08' '2020-09-09' '2020-09-10'
 '2020-09-11' '2020-09-12' '2020-09-13' '2020-09-14' '2020-09-15'
 '2020-09-16' '2020-09-17' '2020-09-18' '2020-09-19' '2020-09-20'
 '2020-09-21' '2020-09-22' '2020-09-23' '2020-09-24' '2020-09-25'
 '2020-09-26' '2020-09-27' '2020-09-28' '2020-09-29' '2020-09-30']


## 21 - Extraiga la parte entera de una matriz aleatoria de números positivos usando 4 métodos diferentes.

`pista: %, np.floor, astype, np.trunc`

In [35]:
Z = np.random.uniform(0,10,10)
print(Z)


print(Z - Z%1)
print(Z // 1)
print(np.floor(Z))
print(Z.astype(int))
print(np.trunc(Z))

[8.876456   9.53943187 3.61946701 4.38200297 8.72189503 4.55199527
 0.5654601  5.77739885 1.76636313 0.50113276]
[8. 9. 3. 4. 8. 4. 0. 5. 1. 0.]
[8. 9. 3. 4. 8. 4. 0. 5. 1. 0.]
[8. 9. 3. 4. 8. 4. 0. 5. 1. 0.]
[8 9 3 4 8 4 0 5 1 0]
[8. 9. 3. 4. 8. 4. 0. 5. 1. 0.]


## 22 - Cree una matriz de 10x10 con valores de fila que van de 0 a 9.

`pista: np.arange`

In [36]:
Z = np.zeros((10,10))
Z = Z + np.arange(10)
print(Z)

[[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]]


In [37]:
# OTRA FORMA: Crear una matriz de 10x10 con valores de fila que van de 0 a 9
matriz_de_10x10 = np.tile(np.arange(10), (10, 1))
matriz_de_10x10

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [38]:
#primero generamos un vector del 1 al 10 que son las lineas que queremos que se repitan
matriz_1010 = np.arange(10).reshape(1,10)
#despues con el np.repeat le pedimos que eso lo repita 10 veces empezando en axis 0
matriz_1010 = np.repeat(matriz_1010, 10, axis=0)
print(matriz_1010)

[[0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]]


## 23 - Cree un vector de tamaño 5 con valores que van de 0 a 1, ambos excluidos.

`pista: np.linspace`

In [39]:
np.linspace(0,1,7)[1:-1]

array([0.16666667, 0.33333333, 0.5       , 0.66666667, 0.83333333])

In [40]:
np.linspace(0,1,6, endpoint=False)[1:]

array([0.16666667, 0.33333333, 0.5       , 0.66666667, 0.83333333])

In [41]:
vector5 = np.linspace(0.01,0.99,5)
vector5

array([0.01 , 0.255, 0.5  , 0.745, 0.99 ])

## 24 - Cree un vector aleatorio de tamaño 25 y ordénelo.

`pista: sort`

In [42]:
vector_25 = np.random.rand(25) #genero vector de 25
print(vector_25) #compruebo
np.sort(vector_25) # el sort hay que llamarlo antes no funciona con el .sort como el reshape


[0.83765596 0.58221727 0.60822633 0.12487498 0.97388837 0.66244608
 0.53365934 0.39699111 0.98569531 0.86142758 0.17553434 0.31343227
 0.29773484 0.56277571 0.72877344 0.17589905 0.33936108 0.89303992
 0.24372648 0.65614802 0.82877095 0.27588448 0.87600603 0.50300807
 0.33978148]


array([0.12487498, 0.17553434, 0.17589905, 0.24372648, 0.27588448,
       0.29773484, 0.31343227, 0.33936108, 0.33978148, 0.39699111,
       0.50300807, 0.53365934, 0.56277571, 0.58221727, 0.60822633,
       0.65614802, 0.66244608, 0.72877344, 0.82877095, 0.83765596,
       0.86142758, 0.87600603, 0.89303992, 0.97388837, 0.98569531])

## 25 - Sume un vector usando `np.add.reduce`.

In [43]:
Z = np.arange(10)
print(Z)
np.add.reduce(Z)

[0 1 2 3 4 5 6 7 8 9]


np.int64(45)

## 26 - Considere dos matrices aleatorias A y B, verifique si son iguales.

`pista: np.allclose, np.array_equal`

In [44]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
print(A)
print(B)
# Si son identicas en forma pero no tienen los mismos valores (hay tolerancia).
equal = np.allclose(A,B)
print(equal)

# Si son identicas en forma y además tienen los mismos valores (no hay tolerancia).
equal = np.array_equal(A,B)
print(equal)

[1 1 1 0 1]
[1 1 1 1 0]
False
False


## 27 - Cree un vector aleatorio de tamaño 25 y reemplace el valor máximo por 0.

`pista: argmax`


In [45]:
y = np.random.random(25)
y[y.argmax()] = 0
print(y)

[0.66097081 0.54436035 0.6782144  0.33756905 0.         0.23535837
 0.21166864 0.62793126 0.91962286 0.66726342 0.94762467 0.84205093
 0.41350877 0.34447169 0.97737054 0.12970298 0.08865971 0.42355917
 0.88064839 0.29619891 0.56768053 0.643863   0.19732731 0.14166013
 0.14457877]


In [46]:
print(vector_25) #imprimo el vector que ya cree en otro ejercicio
maximo = vector_25.max() # ¿cual es el maximo?
print(maximo)
print(np.argmax(vector_25)) #busco la posicion del maximo. Mme dice que es la 9
vector_25_v2 = vector_25[9] = 0
print(vector_25_v2)

[0.83765596 0.58221727 0.60822633 0.12487498 0.97388837 0.66244608
 0.53365934 0.39699111 0.98569531 0.86142758 0.17553434 0.31343227
 0.29773484 0.56277571 0.72877344 0.17589905 0.33936108 0.89303992
 0.24372648 0.65614802 0.82877095 0.27588448 0.87600603 0.50300807
 0.33978148]
0.9856953118160905
8
0


## 28 - ¿Cómo imprimir todos los valores de una matriz?

`pista: np.set_printoptions`

In [47]:
np.set_printoptions(threshold=float("inf"))
Z = np.zeros((10,10))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


## 29 - ¿Cómo encontrar el valor más cercano, a un escalar dado, en un vector?

`pista: argmin`


In [48]:
Z = np.arange(100)
print(Z)
v = np.random.uniform(0,100)
print(v)
index = (np.abs(Z-v)).argmin()
print(np.abs(Z-v))
print(Z[index])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
98.97442808690514
[9.89744281e+01 9.79744281e+01 9.69744281e+01 9.59744281e+01
 9.49744281e+01 9.39744281e+01 9.29744281e+01 9.19744281e+01
 9.09744281e+01 8.99744281e+01 8.89744281e+01 8.79744281e+01
 8.69744281e+01 8.59744281e+01 8.49744281e+01 8.39744281e+01
 8.29744281e+01 8.19744281e+01 8.09744281e+01 7.99744281e+01
 7.89744281e+01 7.79744281e+01 7.69744281e+01 7.59744281e+01
 7.49744281e+01 7.39744281e+01 7.29744281e+01 7.19744281e+01
 7.09744281e+01 6.99744281e+01 6.89744281e+01 6.79744281e+01
 6.69744281e+01 6.59744281e+01 6.49744281e+01 6.39744281e+01
 6.29744281e+01 6.19744281e+01 6.09744281e+01 5.99744281e+01
 5.89744281e+01 5.79744281e+01 5.69744281e+01 5.59744281e+01
 5.49

## 30 - ¿Cómo convertir una matriz `float` (32 bits) en tipo `int` (32 bits)?

`pista: view and [:] =`

In [49]:
# para saber de cuanto tengo que hacer la matriz, tengo que hacer el calculo de los espacios. 
# cada float son 4 bytes. asi que seran 32/4 = 8. 

float_matrix = np.arange(1, 9, dtype=np.float32).reshape(4, 2)
float_matrix

#ahora lo paso a int. para ello se usa view. el simbolo [:] vale para guardarlo como nueva vista sin afectar a float_matrix
int_matrix = float_matrix.view(np.int32)[:]
int_matrix

array([[1065353216, 1073741824],
       [1077936128, 1082130432],
       [1084227584, 1086324736],
       [1088421888, 1090519040]], dtype=int32)

## 31 - ¿Cuál es el equivalente de `enumerate` para matrices en `numpy`?

`pista: np.ndenumerate, np.ndindex`

In [50]:
Z = np.arange(16).reshape(4,4)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(0, 3) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6
(1, 3) 7
(2, 0) 8
(2, 1) 9
(2, 2) 10
(2, 3) 11
(3, 0) 12
(3, 1) 13
(3, 2) 14
(3, 3) 15
(0, 0) 0
(0, 1) 1
(0, 2) 2
(0, 3) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6
(1, 3) 7
(2, 0) 8
(2, 1) 9
(2, 2) 10
(2, 3) 11
(3, 0) 12
(3, 1) 13
(3, 2) 14
(3, 3) 15


## 32 - Restar la media de cada fila a una matriz.

`pista: mean(axis=, keepdims=)`


In [51]:

# Crear una matriz de ejemplo
X = np.array([[10, 20, 30],
                   [40, 50, 60],
                   [70, 80, 90]])

# Calcular la media de cada fila
row_means = X.mean(axis=1, keepdims=True)

# Restar la media de cada fila a la matriz
result = X - row_means

print("Matriz original:")
print(X)

print("\nMedia de cada fila:")
print(row_means)

print("\nMatriz después de restar la media de cada fila:")
print(result)


Matriz original:
[[10 20 30]
 [40 50 60]
 [70 80 90]]

Media de cada fila:
[[20.]
 [50.]
 [80.]]

Matriz después de restar la media de cada fila:
[[-10.   0.  10.]
 [-10.   0.  10.]
 [-10.   0.  10.]]


## 33 - ¿Cómo ordenar una matriz por la enésima columna?

`pista: argsort`

In [52]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print("===========")
print(Z[Z[:,1].argsort()])

[[0 7 9]
 [4 9 4]
 [0 1 0]]
[[0 1 0]
 [0 7 9]
 [4 9 4]]


## 34 - ¿Cómo saber si una matriz 2D tiene columnas nulas?

`pista: any, ~`


In [53]:
# Crear una matriz 2D de ejemplo
matrix = np.array([[1, 2, 0],
                   [4, 5, 0],
                   [7, 8, 0]])

# Comprobar si hay columnas nulas (todas las filas son cero en la columna)
has_null_columns = np.any(np.all(matrix == 0, axis=0))

# Mostrar el resultado
print("Matriz:")
print(matrix)
print("¿Hay columnas nulas?", has_null_columns)


# Explicación del código:
# matrix == 0: Crea una matriz booleana donde cada elemento es True si es igual a 0 y False en caso contrario.
# np.all(..., axis=0): Verifica si todas las filas de cada columna son 0. Esto devuelve un array booleano que indica qué columnas son nulas (True si la columna es nula, False si no).
# np.any(...): Comprueba si hay al menos un valor True en el array booleano resultante, lo que indica que hay al menos una columna nula.



Matriz:
[[1 2 0]
 [4 5 0]
 [7 8 0]]
¿Hay columnas nulas? True


## 35 - Encuentre el valor más cercano de un valor dado en una matriz.

`pista: np.abs, argmin, flat`


In [54]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.6608477818450235
